model: Linear SVM
params:
  C: 1.0
  class_weight: balanced
  dual: auto
  fit_intercept: true
  intercept_scaling: 1
  loss: squared_hinge
  max_iter: 1000
  multi_class: ovr
  penalty: l2
  random_state: null
  tol: 0.0001
  verbose: 0
tfidf:
  max_features: 3000
  ngram_range:
  - 1
  - 2
