model: Logistic Regression
params:
  C: 1.0
  class_weight: balanced
  dual: false
  fit_intercept: true
  intercept_scaling: 1
  l1_ratio: 0.0
  max_iter: 1000
  n_jobs: null
  penalty: deprecated
  random_state: 42
  solver: lbfgs
  tol: 0.0001
  verbose: 0
  warm_start: false
tfidf:
  max_features: 3000
  ngram_range:
  - 1
  - 2
